---
- hosts: localhost
  vars:
   mysql_root_pass: root
  
  tasks:
   - name: install mysql
     apt:
       name: "{{ item }}"
       state: present
     loop:
      - python-mysqldb
      - mysql-server
   
   - name: start mysql
     sudo: yes
     service:
      name: mysql
      state: started
      enabled: true

   - name: update mysql root pass
     sudo: yes
     mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_pass }}"
      login_user: root
      login_password: "{{ mysql_root_pass }}"
      check_implicit_admin: yes 
      priv: "*.*:ALL,GRANT"
      
     with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
