---
# tasks file for jenkins
- name: install wget
  apt:
   name: "{{ item }}"
   state: present
  loop:
   - wget
   - openjdk-8-jre
   - rpm

- name: download jenkins repo
  get_url:
   url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
   dest: /etc/opt/jenkins.repo  

- name: import jenkins key
  rpm_key:
   state: present
   key: https://jenkins-ci.org/redhat/jenkins-ci.org.key


- name: install jenkins
  apt:
   name: jenkins
   state: present

- name: start jenkins
  service:
   name: jenkins
   state: started
   enabled: yes

- name: sleep for 30
  wait_for: timeout=30
  delegate_to: localhost

- name: init password jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_pwd

- name: print pwd  
  debug:
    var: jenkins_pwd.stdout

