---
dependencies: []
galaxy_info:
  author: Rutger de Knijf
  description: Installs a specifiable version of Chromedriver
  company: De Knijf ICT
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: Debian
      versions:
      - jessie
    - name: Ubuntu
      versions:
      - trusty
      - xenial
  galaxy_tags:
    - Chromedriver